#!/usr/bin/env python3
"""Aggregate Massive controlled-scan JSONs, produce CSV + markdown summary,
and re-request missing snapshots with paced retries.
"""
import os
import json
import csv
import glob
import time
import requests
from collections import defaultdict

BASE_DIR = os.path.join("docs", "vendor_evaluation")
SCAN_DIR = os.path.join(BASE_DIR, "samples", "controlled_scan")
OUT_CSV = os.path.join(BASE_DIR, "aggregate_massive_scan.csv")
OUT_MD = os.path.join(BASE_DIR, "170-aggregate-summary.md")
RETRY_DIR = SCAN_DIR
API_URL = "https://api.massive.com/v3/reference/options/contracts"


def load_scan_files():
    files = sorted(glob.glob(os.path.join(SCAN_DIR, "*_asof_*.json")))
    return files


def parse_file(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            j = json.load(f)
    except Exception as e:
        return {"error": f"load-error: {e}", "status_code": None}
    status = j.get("status_code") or j.get("status") or None
    payload = j.get("json") if isinstance(j, dict) and "json" in j else j
    results = []
    if isinstance(payload, dict) and "results" in payload:
        results = payload.get("results") or []
    return {"status_code": status or (payload.get("status") if isinstance(payload, dict) else None), "results": results}


def summarize_results(files):
    rows = []
    missing = []
    per_symbol = defaultdict(list)
    for p in files:
        name = os.path.basename(p)
        if "_asof_" not in name:
            continue
        symbol, rest = name.split("_asof_", 1)
        as_of = rest.replace(".json", "")
        info = parse_file(p)
        status = info.get("status_code")
        res = info.get("results", []) or []
        result_count = len(res)
        exps = [r.get("expiration_date") for r in res if r.get("expiration_date")]
        unique_exps = len(set(exps))
        min_exp = min(exps) if exps else ""
        max_exp = max(exps) if exps else ""
        rows.append({
            "symbol": symbol,
            "as_of": as_of,
            "status_code": status,
            "result_count": result_count,
            "unique_expirations": unique_exps,
            "min_expiration": min_exp,
            "max_expiration": max_exp,
        })
        per_symbol[symbol].append((as_of, result_count, status))
        try:
            sc = int(status) if status is not None else None
        except Exception:
            sc = None
        if (sc is None) or (sc != 200) or (result_count == 0):
            missing.append({"symbol": symbol, "as_of": as_of, "status": status, "result_count": result_count, "path": p})
    return rows, missing, per_symbol


def write_csv(rows):
    keys = ["symbol", "as_of", "status_code", "result_count", "unique_expirations", "min_expiration", "max_expiration"]
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def write_md(per_symbol, missing):
    lines = ["# Aggregate summary — Massive controlled scan\n"]
    lines.append("This file was generated by `scripts/aggregate_massive_scan.py`. It summarizes per-symbol monthly snapshots and lists any missing or empty snapshots that were retried.\n")
    for sym, items in per_symbol.items():
        lines.append(f"## {sym}\n")
        lines.append("| as_of | result_count | status |\n|---|---:|---:|\n")
        for as_of, count, status in sorted(items):
            lines.append(f"| {as_of} | {count} | {status} |\n")
        lines.append("\n")
    if missing:
        lines.append("## Missing / retried snapshots\n")
        lines.append("Snapshots with non-200 or 0 results that will be retried.\n")
        lines.append("| symbol | as_of | status | result_count |\n|---|---|---|---:|\n")
        for m in missing:
            lines.append(f"| {m['symbol']} | {m['as_of']} | {m['status']} | {m['result_count']} |\n")
        lines.append("\n")
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.writelines([l + "\n" if not l.endswith("\n") else l for l in lines])


def retry_missing(missing, max_attempts=5):
    key = os.environ.get("POLYGON_API_KEY") or os.environ.get("MASSIVE_API_KEY")
    if not key:
        print("No POLYGON_API_KEY/MASSIVE_API_KEY found in environment; skipping retries.")
        return []
    retried = []
    session = requests.Session()
    for m in missing:
        symbol = m["symbol"]
        as_of = m["as_of"]
        attempts = 0
        success = False
        last_status = None
        while attempts < max_attempts and not success:
            attempts += 1
            params = {"underlying_ticker": symbol, "as_of": as_of, "limit": 100, "order": "asc", "sort": "ticker", "apiKey": key}
            try:
                r = session.get(API_URL, params=params, timeout=30)
                out = {"url": r.url, "status_code": r.status_code}
                try:
                    out["json"] = r.json()
                except Exception:
                    out["text"] = r.text
                safe_as_of = as_of.replace(":", "_").replace("/", "_")
                fname = os.path.join(RETRY_DIR, f"retry_{symbol}_asof_{safe_as_of}_attempt{attempts}.json")
                with open(fname, "w", encoding="utf-8") as f:
                    json.dump(out, f, indent=2)
                last_status = r.status_code
                print(f"Retried {symbol} {as_of} -> {r.status_code} saved {fname}")
                if r.status_code == 200:
                    success = True
                    retried.append({"symbol": symbol, "as_of": as_of, "attempts": attempts, "status": r.status_code, "file": fname})
                    break
                else:
                    sleep = 5 * (2 ** (attempts - 1))
                    print(f"Backing off {sleep}s (attempt {attempts})")
                    time.sleep(sleep)
            except Exception as e:
                print(f"Error requesting {symbol} {as_of}: {e}")
                time.sleep(5)
        if not success:
            retried.append({"symbol": symbol, "as_of": as_of, "attempts": attempts, "status": last_status, "file": None})
    return retried


def main():
    files = load_scan_files()
    if not files:
        print("No controlled_scan files found in", SCAN_DIR)
        return
    rows, missing, per_symbol = summarize_results(files)
    write_csv(rows)
    write_md(per_symbol, missing)
    print("Wrote:", OUT_CSV, OUT_MD)
    if missing:
        print(f"Found {len(missing)} missing/empty snapshots — attempting retries...")
        retried = retry_missing(missing)
        if retried:
            print("Retry attempts complete — re-aggregating files.")
            rows2, missing2, per_symbol2 = summarize_results(load_scan_files())
            write_csv(rows2)
            write_md(per_symbol2, missing2)
            print("Wrote updated:", OUT_CSV, OUT_MD)
        else:
            print("No retries performed or none succeeded.")


if __name__ == "__main__":
    main()
