#!/usr/bin/env python3
"""
run_pr_review.py — CLI runner for the PR Review Agent.

Usage (local):
    python scripts/run_pr_review.py --pr 42

Usage (CI — called by .github/workflows/pr-review.yml):
    python scripts/run_pr_review.py --pr $PR_NUMBER --post-comment

Behaviour:
  1. Fetches PR metadata + diff via `gh pr view` and `gh pr diff`
  2. Constructs a validated PRMetadata object
  3. Calls review_pull_request() → PRReviewResult
  4. Prints a formatted summary to stdout
  5. If --post-comment: posts findings as a PR comment via `gh pr comment`
  6. Exits 0 if no BLOCKER findings; exits 1 if any BLOCKERs exist (fails CI)

Environment variables:
    LLM_PROVIDER        defaults to "anthropic"
    ANTHROPIC_API_KEY   required for LLM-assisted review
    GH_TOKEN / GITHUB_TOKEN  required for gh CLI authentication in CI
"""

from __future__ import annotations

import argparse
from datetime import datetime
import json
import logging
import subprocess
import sys

from src.agents.pr_review.models import PRMetadata, ReviewSeverity
from src.agents.pr_review.pr_review_agent import review_pull_request

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

_COMMENT_HEADER = "## PR Review Agent\n\n"
_SEVERITY_EMOJI = {
    ReviewSeverity.BLOCKER: "🚫",
    ReviewSeverity.WARNING: "⚠️",
    ReviewSeverity.SUGGESTION: "💡",
}


def _run(cmd: list[str], check: bool = True) -> str:
    """
    Run a subprocess command and return its stdout as a string.

    Args:
        cmd: Command and arguments list.
        check: If True, raise on non-zero exit code.

    Returns:
        stdout stripped of trailing whitespace.

    Raises:
        subprocess.CalledProcessError: On non-zero exit when check=True.
    """
    result = subprocess.run(cmd, capture_output=True, text=True, check=check)  # noqa: S603
    return result.stdout.strip()


def fetch_pr_metadata(pr_number: int) -> PRMetadata:
    """
    Fetch PR metadata and diff from the GitHub CLI.

    Args:
        pr_number: GitHub PR number to review.

    Returns:
        Validated PRMetadata instance.

    Raises:
        subprocess.CalledProcessError: If gh CLI calls fail.
        pydantic.ValidationError: If the returned data fails model validation.
    """
    logger.info("Fetching PR #%d metadata via gh CLI...", pr_number)

    # Fetch structured metadata as JSON
    meta_json = _run(
        [
            "gh",
            "pr",
            "view",
            str(pr_number),
            "--json",
            "number,title,body,baseRefName,headRefName,author,files,createdAt",
        ]
    )
    meta = json.loads(meta_json)

    # Fetch the unified diff
    try:
        diff = _run(["gh", "pr", "diff", str(pr_number)])
    except subprocess.CalledProcessError:
        logger.warning("Could not fetch diff for PR #%d — proceeding without it.", pr_number)
        diff = ""

    changed_files: list[str] = [f["path"] for f in meta.get("files", [])]

    return PRMetadata(
        pr_number=meta["number"],
        title=meta["title"],
        body=meta.get("body") or "",
        base_branch=meta["baseRefName"],
        head_branch=meta["headRefName"],
        author=meta["author"]["login"],
        changed_files=changed_files,
        diff=diff,
        created_at=datetime.fromisoformat(meta["createdAt"].replace("Z", "+00:00")),
    )


def format_comment(result_summary: str, findings_md: str, approved: bool) -> str:
    """
    Build the PR comment body from review results.

    Args:
        result_summary: One-paragraph summary string from PRReviewResult.
        findings_md: Markdown-formatted findings table.
        approved: Whether the PR passed with no blockers.

    Returns:
        Full comment body as a markdown string.
    """
    status_line = (
        "**Status: ✅ No blockers — eligible for merge (human approval required)**"
        if approved
        else "**Status: 🚫 Blockers found — must be resolved before merge**"
    )
    return (
        f"{_COMMENT_HEADER}"
        f"{status_line}\n\n"
        f"{result_summary}\n\n"
        f"{findings_md}"
        f"\n\n---\n*Generated by PR Review Agent — [source](src/agents/pr_review/)*"
    )


def findings_to_markdown(result: PRReviewResult) -> str:  # type: ignore[name-defined]  # noqa: F821
    """
    Render PRReviewResult findings as a markdown table.

    Args:
        result: Completed PRReviewResult from review_pull_request().

    Returns:
        Markdown string; empty string if there are no findings.
    """

    if not result.findings:
        return "_No findings._"

    lines = [
        "| Severity | File | Rule | Message |",
        "|----------|------|------|---------|",
    ]
    for f in result.findings:
        emoji = _SEVERITY_EMOJI.get(f.severity, "")
        loc = f.location
        if f.line_number:
            loc = f"{loc}:{f.line_number}"
        msg = f.message.replace("|", "\\|")
        if f.suggestion:
            msg += f" _{f.suggestion.replace('|', chr(92) + '|')}_"
        lines.append(f"| {emoji} {f.severity.value} | `{loc}` | `{f.rule}` | {msg} |")

    return "\n".join(lines)


def post_comment(pr_number: int, body: str) -> None:
    """
    Post a comment to a GitHub PR via the gh CLI.

    Args:
        pr_number: GitHub PR number.
        body: Markdown comment body.
    """
    logger.info("Posting review comment to PR #%d...", pr_number)
    _run(["gh", "pr", "comment", str(pr_number), "--body", body])
    logger.info("Comment posted to PR #%d.", pr_number)


def main() -> int:
    """
    Entry point for the PR review runner.

    Returns:
        0 if no BLOCKER findings; 1 if any BLOCKERs exist.
    """
    parser = argparse.ArgumentParser(
        description="Run the PR Review Agent against a GitHub pull request."
    )
    parser.add_argument(
        "--pr",
        type=int,
        required=True,
        metavar="NUMBER",
        help="GitHub PR number to review",
    )
    parser.add_argument(
        "--post-comment",
        action="store_true",
        help="Post findings as a PR comment via gh CLI",
    )
    args = parser.parse_args()

    # Fetch PR data
    try:
        metadata = fetch_pr_metadata(args.pr)
    except Exception as exc:
        logger.error("Failed to fetch PR #%d metadata: %s", args.pr, exc)
        return 1

    # Run review
    result = review_pull_request(metadata)

    # Log summary via logger
    logger.info("%s", "\n" + "=" * 70)
    logger.info(
        "PR #%d Review — %s",
        result.pr_number,
        result.reviewed_at.strftime("%Y-%m-%d %H:%M UTC"),
    )
    logger.info("%s", "=" * 70)
    logger.info(result.summary)

    if result.findings:
        logger.info("Findings (%d):", len(result.findings))
        for f in result.findings:
            emoji = _SEVERITY_EMOJI.get(f.severity, "")
            loc = f.location + (f":{f.line_number}" if f.line_number else "")
            logger.info("  %s [%s] %s @ %s", emoji, f.severity.value.upper(), f.rule, loc)
            logger.info("     %s", f.message)
            if f.suggestion:
                logger.info("     → %s", f.suggestion)
    else:
        logger.info("No findings.")

    logger.info("%s", "=" * 70 + "\n")

    # Optionally post comment to PR
    if args.post_comment:
        findings_md = findings_to_markdown(result)
        comment_body = format_comment(result.summary, findings_md, result.approved)
        try:
            post_comment(args.pr, comment_body)
        except Exception as exc:
            logger.error("Failed to post comment to PR #%d: %s", args.pr, exc)
            # Non-fatal — do not block CI exit code for comment failure

    return 0 if result.approved else 1


if __name__ == "__main__":
    sys.exit(main())
